// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package proxy

import (
	"github.com/gopcua/opcua"
	"sync"
)

// Ensure, that OPCUAClientMock does implement OPCUAClient.
// If this is not the case, regenerate this file with moq.
var _ OPCUAClient = &OPCUAClientMock{}

// OPCUAClientMock is a mock implementation of OPCUAClient.
//
// 	func TestSomethingThatUsesOPCUAClient(t *testing.T) {
//
// 		// make and configure a mocked OPCUAClient
// 		mockedOPCUAClient := &OPCUAClientMock{
// 			StateFunc: func() opcua.ConnState {
// 				panic("mock out the State method")
// 			},
// 		}
//
// 		// use mockedOPCUAClient in code that requires OPCUAClient
// 		// and then make assertions.
//
// 	}
type OPCUAClientMock struct {
	// StateFunc mocks the State method.
	StateFunc func() opcua.ConnState

	// calls tracks calls to the methods.
	calls struct {
		// State holds details about calls to the State method.
		State []struct {
		}
	}
	lockState sync.RWMutex
}

// State calls StateFunc.
func (mock *OPCUAClientMock) State() opcua.ConnState {
	if mock.StateFunc == nil {
		panic("OPCUAClientMock.StateFunc: method is nil but OPCUAClient.State was just called")
	}
	callInfo := struct {
	}{}
	mock.lockState.Lock()
	mock.calls.State = append(mock.calls.State, callInfo)
	mock.lockState.Unlock()
	return mock.StateFunc()
}

// StateCalls gets all the calls that were made to State.
// Check the length with:
//     len(mockedOPCUAClient.StateCalls())
func (mock *OPCUAClientMock) StateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockState.RLock()
	calls = mock.calls.State
	mock.lockState.RUnlock()
	return calls
}
