version: "3.4"

services:

  opcua-server-first:
    image: mcr.microsoft.com/iotedge/opc-plc:2.12.30
    command:
      - --plchostname=opcua-server-first
      - --unsecuretransport
    user: ${OPCUA_SERVER_UID}:${OPCUA_SERVER_GID}
    volumes:
      - ./pki-server:/app/pki

  opcua-server-second:
    image: mcr.microsoft.com/iotedge/opc-plc:2.12.30
    command:
      - --plchostname=opcua-server-second
      - --disableanonymousauth
    user: ${OPCUA_SERVER_UID}:${OPCUA_SERVER_GID}
    volumes:
      - ./pki-server:/app/pki

  mongodb:
    image: mongo:7.0
    volumes:
      - ./initial-data.mongodb:/usr/src/initial-data.mongodb
      - ./tests.mongodb:/usr/src/tests.mongodb:ro

  config-api:
    build: ./config-api
    ports:
      - 3000:3000
    volumes:
      - ./config-api/config.json:/usr/src/config.json:ro

  opcua-proxy:
    build: ..
    command:
      - /usr/local/bin/opcua-proxy
      - --verbose
    environment:
      - MONGODB_DATABASE=opcua
      - CONFIG_API_URL=http://config-api:3000/config
      - PKI_DIR=/pki
    volumes:
      - ./pki-client:/pki:ro
