services:

  opcua-server-first:
    image: mcr.microsoft.com/iotedge/opc-plc:2.14.1
    command:
      - --plchostname=opcua-server-first
      - --unsecuretransport
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - find /app/pki/own/certs -mindepth 1 -maxdepth 1 | read
      interval: 5s
      timeout: 5s
    user: ${OPCUA_SERVER_UID:?}:${OPCUA_SERVER_GID:?}
    volumes:
      - ./pki-server-first:/app/pki

  opcua-server-second:
    image: mcr.microsoft.com/iotedge/opc-plc:2.14.1
    command:
      - --plchostname=opcua-server-second
      - --disableanonymousauth
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - find /app/pki/own/certs -mindepth 1 -maxdepth 1 | read
      interval: 5s
      timeout: 5s
    user: ${OPCUA_SERVER_UID:?}:${OPCUA_SERVER_GID:?}
    volumes:
      - ./pki-server-second:/app/pki

  centrifugo:
    image: centrifugo/centrifugo:v6.6
    command:
      - centrifugo
      - --config
      - config.toml
    healthcheck:
      test:
        - CMD
        - wget
        - --quiet
        - --spider
        - http://127.0.0.1:8000/health
      interval: 5s
      timeout: 5s
    volumes:
      - ./centrifugo/centrifugo.toml:/centrifugo/config.toml

  deno:
    build: ./deno

  opcua-proxy:
    build: ..
    command:
      - /usr/local/bin/opcua-proxy
      - --verbose
    environment:
      - CENTRIFUGO_SERVER_URI=http://centrifugo:10000
      - CENTRIFUGO_API_KEY=_KVYg9XcxidaiOJrYR5igP-MlY3VJ8Vz6BjaCQcvgb_XF98E_R8Ohv0cjHscp9GBEEjvvOlCDYurZlQgSTqBuA
      - CENTRIFUGO_NAMESPACE=integration.tests
      - CONFIG_API_URL=http://deno:3000/config
      - PKI_DIR=/pki
    healthcheck:
      interval: 5s
      timeout: 5s
    mem_limit: 2g
    volumes:
      - ./pki-client:/pki:ro
